// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weby2019.models;

namespace weby2019.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20191225151542_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("weby2019.models.Slovo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("skore");

                    b.HasKey("Id");

                    b.ToTable("Slova");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "šiška",
                            skore = 6
                        },
                        new
                        {
                            Id = 2,
                            Name = "hřeben",
                            skore = 6
                        },
                        new
                        {
                            Id = 3,
                            Name = "sloupec",
                            skore = 6
                        },
                        new
                        {
                            Id = 4,
                            Name = "řádek",
                            skore = 6
                        },
                        new
                        {
                            Id = 5,
                            Name = "míč",
                            skore = 6
                        },
                        new
                        {
                            Id = 6,
                            Name = "pětka",
                            skore = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "okno",
                            skore = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "papír",
                            skore = 6
                        },
                        new
                        {
                            Id = 9,
                            Name = "stěna",
                            skore = 6
                        },
                        new
                        {
                            Id = 10,
                            Name = "kámen",
                            skore = 6
                        },
                        new
                        {
                            Id = 11,
                            Name = "nůž",
                            skore = 6
                        },
                        new
                        {
                            Id = 12,
                            Name = "houby",
                            skore = 6
                        },
                        new
                        {
                            Id = 13,
                            Name = "slovník",
                            skore = 6
                        },
                        new
                        {
                            Id = 14,
                            Name = "letadlo",
                            skore = 6
                        },
                        new
                        {
                            Id = 15,
                            Name = "světlo",
                            skore = 6
                        },
                        new
                        {
                            Id = 16,
                            Name = "housenka",
                            skore = 6
                        },
                        new
                        {
                            Id = 17,
                            Name = "koleno",
                            skore = 6
                        },
                        new
                        {
                            Id = 18,
                            Name = "slovo",
                            skore = 6
                        },
                        new
                        {
                            Id = 19,
                            Name = "požár",
                            skore = 6
                        },
                        new
                        {
                            Id = 20,
                            Name = "strom",
                            skore = 6
                        },
                        new
                        {
                            Id = 21,
                            Name = "voda",
                            skore = 6
                        },
                        new
                        {
                            Id = 22,
                            Name = "kočka",
                            skore = 6
                        },
                        new
                        {
                            Id = 23,
                            Name = "železo",
                            skore = 6
                        },
                        new
                        {
                            Id = 24,
                            Name = "kolo",
                            skore = 6
                        },
                        new
                        {
                            Id = 25,
                            Name = "platina",
                            skore = 6
                        },
                        new
                        {
                            Id = 26,
                            Name = "papoušek",
                            skore = 6
                        },
                        new
                        {
                            Id = 27,
                            Name = "skočit",
                            skore = 6
                        },
                        new
                        {
                            Id = 28,
                            Name = "houkat",
                            skore = 6
                        },
                        new
                        {
                            Id = 29,
                            Name = "růst",
                            skore = 6
                        },
                        new
                        {
                            Id = 30,
                            Name = "strop",
                            skore = 6
                        },
                        new
                        {
                            Id = 31,
                            Name = "vařit",
                            skore = 6
                        },
                        new
                        {
                            Id = 32,
                            Name = "ponožka",
                            skore = 6
                        },
                        new
                        {
                            Id = 33,
                            Name = "smrdí",
                            skore = 6
                        },
                        new
                        {
                            Id = 34,
                            Name = "házet",
                            skore = 6
                        },
                        new
                        {
                            Id = 35,
                            Name = "kopat",
                            skore = 6
                        },
                        new
                        {
                            Id = 36,
                            Name = "hotel",
                            skore = 6
                        },
                        new
                        {
                            Id = 37,
                            Name = "pole",
                            skore = 6
                        },
                        new
                        {
                            Id = 38,
                            Name = "užovka",
                            skore = 6
                        },
                        new
                        {
                            Id = 39,
                            Name = "hora",
                            skore = 6
                        },
                        new
                        {
                            Id = 40,
                            Name = "led",
                            skore = 6
                        },
                        new
                        {
                            Id = 41,
                            Name = "len",
                            skore = 6
                        },
                        new
                        {
                            Id = 42,
                            Name = "sen",
                            skore = 6
                        },
                        new
                        {
                            Id = 43,
                            Name = "ven",
                            skore = 6
                        },
                        new
                        {
                            Id = 44,
                            Name = "zem",
                            skore = 6
                        },
                        new
                        {
                            Id = 45,
                            Name = "hodiny",
                            skore = 6
                        },
                        new
                        {
                            Id = 46,
                            Name = "slimák",
                            skore = 6
                        },
                        new
                        {
                            Id = 47,
                            Name = "pes",
                            skore = 6
                        },
                        new
                        {
                            Id = 48,
                            Name = "hák",
                            skore = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
